# Usar a imagem base do Python
FROM python:3.10-slim

# Configurar o diretório de trabalho no container
WORKDIR /app

# Copiar os arquivos de requisitos
COPY requirements.txt .

# Instalar dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o código do projeto para o container
COPY . .

# Configurar o Django para rodar no ambiente de produção
ENV PYTHONUNBUFFERED 1

# Abrir a porta 8000 para o servidor
EXPOSE 8000

# Comando padrão para rodar o servidor
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
